name: Saludo

on:
	push:
branches:
	- main
	- develop

env:
	Nombre: 'Diego Escobedo Bopp'

jobs:
	saludo:
		runs-om: ubuntu-latest
		steps:
			-name: Saludo desde main
			if: gitHub.ref == 'refs/heads/main'
			run: echo "Hola desde main, soy $Nombre"

			-name: Saludo desde develop
			if: gitHub.ref == 'refs/heads/develop'
			run: echo "Hola desde develop, soy $Nombre"

