name: Saludo

on:
	push:
		branches:
		    - main
		    - develop

jobs:
	saludo:
		runs-om: ubuntu-latest
		steps:
			-name: Saludo desde main
			run: echo "Hola desde main, soy Diego Escobedo"

			-name: Saludo desde develop
			run: echo "Hola desde develop, soy Diego Escobedo"

